
	          <m:item name='小说栏目管理' link='story_catalog.php' rank='story_catalog' target='main' />
	          <m:item name='小说书目' link='story_books.php' rank='story_list' target='main' />
	          <m:item name='小说连载内容' link='story_list_content.php' rank='story_list' target='main' />
	          <m:item name='小说章节管理' link='story_list_chapter.php' rank='story_list' target='main' />
	          <m:item name='更新小说HTML' link='makehtml_story.php' rank='sys_MakeHtml' target='main' />
                  <m:item name='评论管理' link='story_feedback_main.php' rank='sys_MakeHtml' target='main' />
	      