<?php
$z[0]=Array("item","",2,85);
$z[0][4]['name']="分类设置";
$z[0][4]['link']="group_store.php";
$z[0][4]['rank']="group_All";
$z[0][4]['target']="main";
$z[1]=Array("item","",87,169);
$z[1][4]['name']="圈子列表";
$z[1][4]['link']="group_main.php";
$z[1][4]['rank']="group_All";
$z[1][4]['target']="main";
$z[2]=Array("item","",171,256);
$z[2][4]['name']="主题管理";
$z[2][4]['link']="group_threads.php";
$z[2][4]['rank']="group_All";
$z[2][4]['target']="main";

?>