
-----------------------------------------------
<m:top name='模块管理' c='6,' display='block'>
    <m:item name='模块管理' link='module_main.php' rank='sys_module' target='main' />
    <m:item name='上传新模块' link='module_upload.php' rank='sys_module' target='main' />
    <m:item name='模块生成向导' link='module_make.php' rank='sys_module' target='main' />
    </m:top>
<m:top item='7' name='辅助插件' display='block'>
  <m:item name='插件管理器' link='plus_main.php' rank='10' target='main' />
  <m:item name='挑错管理' link='erraddsave.php' rank='plus_挑错管理' target='main' />
<m:item name='百度新闻' link='baidunews.php' rank='plus_百度新闻' target='main' />
<m:item name='文件管理器' link='file_manage_main.php' rank='plus_文件管理器' target='main' />
<m:item name='广告管理' link='ad_main.php' rank='plus_广告管理' target='main' />
<m:item name='友情链接' link='friendlink_main.php' rank='plus_友情链接模块' target='main' />
<m:item name='投票模块' link='vote_main.php' rank='plus_投票模块' target='main' />
<m:item name='bShare分享插件' link='plus_bshare.php' rank='plus_bShare分享插件' target='main' />
<m:item name='留言簿模块' link='catalog_do.php?dopost=guestbook' rank='plus_留言簿模块' target='main' />
<m:item name='站内新闻发布' link='mynews_main.php' rank='plus_站内新闻发布' target='main' />
<m:item name='邮件订阅' link='mail_send.php' rank='plus_Mail' target='main' />

</m:top>

<m:top name='圈子管理' c='6,' display='block'>
<m:item name='分类设置' link='group_store.php' rank='group_All' target='main'/>
<m:item name='圈子列表' link='group_main.php' rank='group_All' target='main'/>
<m:item name='主题管理' link='group_threads.php' rank='group_All' target='main'/>
</m:top>
<m:top name='邮件订阅' c='6,' display='block' rank='plus_Mail'>
  <m:item name='会员邮件管理' link='mail_send.php' rank='plus_Mail' target='main' />
  <m:item name='订阅期刊管理' link='mail_title.php' rank='plus_Mail' target='main' />
  <m:item name='订阅分类管理' link='mail_type.php' rank='plus_Mail' target='main' />
  <m:item name='群发期刊管理' link='mail_title_send.php' rank='plus_Mail' target='main' />
  <m:item name='获取邮件地址' link='mail_getfile.php' rank='plus_Mail' target='main' />、
  <m:item name='邮件列表管理' link='mail_file_manage.php' rank='plus_Mail' target='main' />
</m:top>
<m:top name='问答管理' c='6,' display='block' rank=''>
  <m:item name='栏目管理' link='../ask/admin.php?ct=asktype' rank='' target='main' />
  <m:item name='问题管理' link='../ask/admin.php?ct=issue' rank='' target='main' />
  <m:item name='答案管理' link='../ask/admin.php?ct=answer' rank='' target='main' />
  <m:item name='幻灯片管理' link='../ask/admin.php?ct=slide' rank='' target='main' />
</m:top>
<m:top name='UCenter模块' c='6,' display='block' rank=''>
<m:item name='UCenter配置' link='api_ucenter.php' rank='' target='main' />
</m:top>


              <m:top name='小说管理' display='block' c='6,' rank=''>
	          <m:item name='小说栏目管理' link='story_catalog.php' rank='story_catalog' target='main' />
	          <m:item name='小说书目' link='story_books.php' rank='story_list' target='main' />
	          <m:item name='小说连载内容' link='story_list_content.php' rank='story_list' target='main' />
	          <m:item name='小说章节管理' link='story_list_chapter.php' rank='story_list' target='main' />
	          <m:item name='更新小说HTML' link='makehtml_story.php' rank='sys_MakeHtml' target='main' />
                  <m:item name='评论管理' link='story_feedback_main.php' rank='sys_MakeHtml' target='main' />
	      </m:top>









-----------------------------------------------
