
  <m:item name='会员邮件管理' link='mail_send.php' rank='plus_Mail' target='main' />
  <m:item name='订阅期刊管理' link='mail_title.php' rank='plus_Mail' target='main' />
  <m:item name='订阅分类管理' link='mail_type.php' rank='plus_Mail' target='main' />
  <m:item name='群发期刊管理' link='mail_title_send.php' rank='plus_Mail' target='main' />
  <m:item name='获取邮件地址' link='mail_getfile.php' rank='plus_Mail' target='main' />、
  <m:item name='邮件列表管理' link='mail_file_manage.php' rank='plus_Mail' target='main' />
